### ISSUE TITLE
When creating a new project fails. Error – creating project <PROJECT-NAME> failed. Project already exists.

### ISSUE THREAD

**Issue by rjrosa** [keptn/keptn#8481]
Solution listed below did not resolve the issue:
Similar issue reported:  https://github.com/keptn/keptn/issues/930

Client OS: macOS.

Keptn CLI Version: 0.14.1
Keptn cluster version: 0.16.0

Kubernetes cloud provider: AWS

Kubernetes version: 
![image](https://user-images.githubusercontent.com/102756323/180015770-f6c74b8b-2662-4b66-8a47-c01dde5f7bc6.png)

Others components:
image: docker.io/nginxinc/nginx-unprivileged:1.22.0.-alpine

Component affected: Datastore

Bug description: When I try to create new project, I get "project already exists" error.   If I try to delete it:  I get "project not found" error. 

I'm able to login into Keptn-Bridge using Nginx Ingress.

To Replicate:
I tear down the Kubernetes cluster and rebuild it, also re-install all tools needed, among them Keptn.   When I tried to provision the project from Keptn CLI :
keptn create project $PROJECT_NAME --shipyard=$KEPTN_SHIPYARD \
--git-user=$GIT_USER --git-remote-url=$GIT_REMOTE_URL --git-token=$GIT_TOKEN

Starting to create project
Error: Create project was unsuccessful.
Project already exists

Also I tried to update:
keptn update project $PROJECT_NAME  --git-user=$GIT_USER --git-token=$GIT_TOKEN --git-remote-url=$GIT_REMOTE_URL
Starting to update project
Error: Update project was unsuccessful. Received unexpected response: 500 500 Internal Server Error

When I tried to delete, got the following:
keptn delete project $PROJECT_NAME
Starting to delete project
Could not retrieve information about project PROJECT_NAME: Project not found: PROJECT_NAME
Error: Could not retrieve information about project PROJECT_NAME: Project not found: PROJECT_NAME

Expected behavior: To be able to create the project 

Screenshots:
![image](https://user-images.githubusercontent.com/102756323/180019042-f35d319f-dc0b-4720-b1b6-45c8b95aa8c4.png)

![image](https://user-images.githubusercontent.com/102756323/180019103-0d7f81f9-2c74-4ba4-891d-20c4d9ca26b2.png)

**Comment by bacherfl** [comment]
Hi @rjrosa can you please also add some logs from the shipyard-controller and the resource-service to this issue? You can retrieve them with the following commands:

```
kubectl logs -n keptn deployment/shipyard-controller
kubectl logs -n keptn deployment/resource-service
```

Also, in the issue description it says that your Keptn CLI Version is at version 0.14.1, while the Keptn Cluster Version is 0.16.0 - Is that correct? If yes, please try to also upgrade your Keptn CLI to 0.16.0 and check if that problem still occurs

**Comment by rjrosa** [comment]
Brew upgrade keptn

keptn version



Keptn CLI version: 0.17.0

Keptn cluster version: 0.16.0



Daily version check is disabled.

Keptn will not collect statistical data and will not notify about new versions and security patches for Keptn. Details can be found at: https://keptn.sh/docs/0.17.x/reference/version_check

---------------------------------------------------

* To enable the daily version check, please execute:

 - keptn set config AutomaticVersionCheck true





Log files:
Keptn-Controller log<file:///Users/robinson.rosa/Downloads/kept-controller.log>

Keptn-Service log<file:///Users/robinson.rosa/Downloads/kept-service.log>


From: Florian Bacher ***@***.***>
Date: Tuesday, July 26, 2022 at 5:50 AM
To: keptn/keptn ***@***.***>
Cc: Robinson Rosa ***@***.***>, Mention ***@***.***>
Subject: Re: [keptn/keptn] When creating a new project fails. Error – creating project <PROJECT-NAME> failed. Project already exists. (Issue #8481)
Hi @⁠​rjrosa can you please also add some logs from the shipyard-controller and the resource-service to this issue? You can retrieve them with the following commands:⁠​ kubectl logs -n keptn deployment/shipyard-controller kubectl logs -n keptn


Hi @rjrosa<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Furldefense.com%2Fv3%2F__https%3A%2F%2Fgithub.com%2Frjrosa__%3B!!CsXUvQARd5I!eCyWxF08fHB5sSX8puaX6xHEtBcoKBd5u_PAU2joOemU5pApPZ7IAyIenZOcFftyo5udfaj_LqKxfN2SL8IOJFD0CwicWw%24&data=05%7C01%7Crobinson.rosa%40madmobile.com%7C1bb429984e8446e50eb908da6eec55a1%7C0edabf895e1342c3abd6f687e9fe0f3a%7C0%7C0%7C637944258584794178%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=uZpAgka3FYMEoYC8N0Gk9RQhD1kZeX1iomdqM9Os1VY%3D&reserved=0> can you please also add some logs from the shipyard-controller and the resource-service to this issue? You can retrieve them with the following commands:

kubectl logs -n keptn deployment/shipyard-controller

kubectl logs -n keptn deployment/resource-service

Also, in the issue description it says that your Keptn CLI Version is at version 0.14.1, while the Keptn Cluster Version is 0.16.0 - Is that correct? If yes, please try to also upgrade your Keptn CLI to 0.16.0 and check if that problem still occurs

**Comment by rjrosa** [comment]
===============================================
Controller log:
===============================================
2022/07/26 14:16:43 [Recovery] 2022/07/26 - 14:16:43 panic recovered:
runtime error: invalid memory address or nil pointer dereference
/usr/local/go/src/runtime/panic.go:220 (0x44bc55)
/usr/local/go/src/runtime/signal_unix.go:818 (0x44bc25)
/go/src/github.com/keptn/keptn/shipyard-controller/handler/projectmanager.go:193 (0x15cd8ad)
/go/src/github.com/keptn/keptn/shipyard-controller/handler/projecthandler.go:375 (0x15caa8d)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168 (0x15c7a0c)
/go/src/github.com/keptn/keptn/shipyard-controller/handler/gracefulshutdownmiddleware.go:13 (0x15c79f3)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168 (0x925281)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/recovery.go:99 (0x92526c)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168 (0x9243a6)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/logger.go:241 (0x924389)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168 (0x923470)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/gin.go:555 (0x9230d8)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/gin.go:511 (0x922c11)
/usr/local/go/src/net/http/server.go:2916 (0x6d469a)
/usr/local/go/src/net/http/server.go:1966 (0x6cf696)
/usr/local/go/src/runtime/asm_amd64.s:1571 (0x4666c0)

time="2022-07-26T14:17:27Z" level=info msg="Received event of type sh.keptn.event.project.create.started from shipyard-controller for project devsecops"
time="2022-07-26T14:17:27Z" level=info msg="Unable to handle task event: unable to handle 'task.finished' event: event does not contain a stage: invalid event scope"
time="2022-07-26T14:17:27Z" level=error msg="Error occurred while creating project in configuration service: upstream repository not found"
time="2022-07-26T14:17:27Z" level=info msg="Rollback: Try to delete GIT repository credentials secret for project devsecops"
time="2022-07-26T14:17:27Z" level=info msg="deleting git credentials for project devsecops"
time="2022-07-26T14:17:27Z" level=info msg="deleted git credentials for project devsecops"
time="2022-07-26T14:17:29Z" level=info msg="Received event of type sh.keptn.event.project.create.finished from shipyard-controller for project devsecops"
time="2022-07-26T14:17:29Z" level=info msg="Unable to handle task event: unable to handle 'task.finished' event: event does not contain a stage: invalid event scope"
time="2022-07-26T14:18:56Z" level=info msg="Received event of type sh.keptn.event.project.create.started from shipyard-controller for project devsecops"
time="2022-07-26T14:18:56Z" level=info msg="Unable to handle task event: unable to handle 'task.finished' event: event does not contain a stage: invalid event scope"
time="2022-07-26T14:18:56Z" level=error msg="Error occurred while creating project in configuration service: upstream repository not found"
time="2022-07-26T14:18:56Z" level=info msg="Rollback: Try to delete GIT repository credentials secret for project devsecops"
time="2022-07-26T14:18:56Z" level=info msg="deleting git credentials for project devsecops"
time="2022-07-26T14:18:56Z" level=info msg="Received event of type sh.keptn.event.project.create.finished from shipyard-controller for project devsecops"
time="2022-07-26T14:18:56Z" level=info msg="Unable to handle task event: unable to handle 'task.finished' event: event does not contain a stage: invalid event scope"
time="2022-07-26T14:18:56Z" level=info msg="deleted git credentials for project devsecops"
time="2022-07-26T14:19:18Z" level=info msg="Received event of type sh.keptn.event.project.create.started from shipyard-controller for project devsecops"
time="2022-07-26T14:19:18Z" level=info msg="Unable to handle task event: unable to handle 'task.finished' event: event does not contain a stage: invalid event scope"
time="2022-07-26T14:19:18Z" level=error msg="Error occurred while creating project in configuration service: upstream repository not found"
time="2022-07-26T14:19:18Z" level=info msg="Rollback: Try to delete GIT repository credentials secret for project devsecops"
time="2022-07-26T14:19:18Z" level=info msg="deleting git credentials for project devsecops"
time="2022-07-26T14:19:18Z" level=info msg="Received event of type sh.keptn.event.project.create.finished from shipyard-controller for project devsecops"
time="2022-07-26T14:19:18Z" level=info msg="Unable to handle task event: unable to handle 'task.finished' event: event does not contain a stage: invalid event scope"
time="2022-07-26T14:19:18Z" level=info msg="deleted git credentials for project devsecops"
time="2022-07-26T14:19:38Z" level=info msg="Received event of type sh.keptn.event.project.create.started from shipyard-controller for project devsecops"
time="2022-07-26T14:19:38Z" level=info msg="Unable to handle task event: unable to handle 'task.finished' event: event does not contain a stage: invalid event scope"
time="2022-07-26T14:19:38Z" level=error msg="Error occurred while creating project in configuration service: upstream repository not found"
time="2022-07-26T14:19:38Z" level=info msg="Rollback: Try to delete GIT repository credentials secret for project devsecops"
time="2022-07-26T14:19:38Z" level=info msg="deleting git credentials for project devsecops"
time="2022-07-26T14:19:38Z" level=info msg="Received event of type sh.keptn.event.project.create.finished from shipyard-controller for project devsecops"
time="2022-07-26T14:19:38Z" level=info msg="Unable to handle task event: unable to handle 'task.finished' event: event does not contain a stage: invalid event scope"
time="2022-07-26T14:19:38Z" level=info msg="deleted git credentials for project devsecops"

**Comment by rjrosa** [comment]
After the CLI upgrade now started to gitURI error: 
===============================================
Service log
===============================================
time="2022-07-19T17:33:26Z" level=info msg="Could not complete request POST /v1/project: project already exists"
time="2022-07-19T17:33:27Z" level=info msg="Could not complete request POST /v1/project: project already exists"
time="2022-07-19T17:33:29Z" level=info msg="Could not complete request POST /v1/project: project already exists"
time="2022-07-19T17:33:32Z" level=info msg="Could not complete request POST /v1/project: project already exists"
time="2022-07-19T17:35:32Z" level=info msg="Could not complete request POST /v1/project: project already exists"
time="2022-07-19T17:35:33Z" level=info msg="Could not complete request POST /v1/project: project already exists"
time="2022-07-19T17:35:35Z" level=info msg="Could not complete request POST /v1/project: project already exists"
time="2022-07-19T17:35:38Z" level=info msg="Could not complete request POST /v1/project: project already exists"
time="2022-07-19T18:07:06Z" level=info msg="Could not complete request POST /v1/project: project already exists"
time="2022-07-20T13:07:55Z" level=info msg="Could not complete request POST /v1/project: project already exists"
time="2022-07-20T13:36:38Z" level=info msg="Could not complete request POST /v1/project: project already exists"
time="2022-07-20T13:39:43Z" level=info msg="Could not complete request POST /v1/project: could not read credentials for project devsecops: invalid remote URI"
time="2022-07-20T14:07:51Z" level=info msg="Could not complete request POST /v1/project: project already exists"
time="2022-07-20T15:11:09Z" level=info msg="Could not complete request POST /v1/project: project already exists"
time="2022-07-20T20:04:31Z" level=info msg="Could not complete request POST /v1/project: project already exists"
time="2022-07-20T20:04:32Z" level=info msg="Could not complete request POST /v1/project: project already exists"
time="2022-07-20T20:04:34Z" level=info msg="Could not complete request POST /v1/project: project already exists"
time="2022-07-20T20:04:37Z" level=info msg="Could not complete request POST /v1/project: project already exists"
time="2022-07-20T20:05:03Z" level=info msg="Could not complete request POST /v1/project: project already exists"
time="2022-07-20T20:05:04Z" level=info msg="Could not complete request POST /v1/project: project already exists"
time="2022-07-20T20:05:06Z" level=info msg="Could not complete request POST /v1/project: project already exists"
time="2022-07-20T20:05:09Z" level=info msg="Could not complete request POST /v1/project: project already exists"
time="2022-07-26T13:50:07Z" level=info msg="Could not complete request POST /v1/project: could not read credentials for project devsecops: invalid remote URI"
time="2022-07-26T13:51:03Z" level=info msg="Could not complete request POST /v1/project: could not read credentials for project devsecops: invalid remote URI"
time="2022-07-26T13:52:34Z" level=info msg="Could not complete request POST /v1/project: could not read credentials for project devsecops: invalid remote URI"
time="2022-07-26T14:14:19Z" level=info msg="Could not complete request POST /v1/project: could not read credentials for project devsecops: invalid remote URI"
time="2022-07-26T14:17:27Z" level=info msg="Could not complete request POST /v1/project: could not read credentials for project devsecops: invalid remote URI"
time="2022-07-26T14:18:56Z" level=info msg="Could not complete request POST /v1/project: could not read credentials for project devsecops: invalid remote URI"
time="2022-07-26T14:19:18Z" level=info msg="Could not complete request POST /v1/project: could not read credentials for project devsecops: invalid remote URI"
time="2022-07-26T14:19:38Z" level=info msg="Could not complete request POST /v1/project: could not read credentials for project devsecops: invalid remote URI"

**Comment by bacherfl** [comment]
Thanks for the logs - There was a change in the structure of the git credentials that is sent to the API by the CLI when creating a project. That is most likely why you are seeing this error. Since right now you have v0.17 of the CLI installed locally, can you please try to upgrade the Keptn installation in your Cluster to 0.17 as well? Using Keptn 0.16 in combination with the 0.17 CLI will not work due to the aforementioned change, so it is important that the version numbers match in this case.

**Comment by ElliotDavis** [comment]
I am also having the same issue when trying to run the provided demos.   I am on a mac M1 , running lates keptn  cli and on cluster.  When I  run keptn create project $PROJECT_NAME --shipyard=./shipyard.yaml --git-user=$GIT_USER --git-remote-url=$GIT_REMOTE_URL --git-token=$GIT_TOKEN I get 

Starting to create project
Error: Create project was unsuccessful.
Project already exists"
error.  
See attached logs
![Screen Shot 2022-07-31 at 4 51 33 PM](https://user-images.githubusercontent.com/20953351/182050760-dd822591-65cc-4aab-b293-575e77d429a5.png)
![Screen Shot 2022-07-31 at 4 50 55 PM](https://user-images.githubusercontent.com/20953351/182050761-4fd6c824-cb1a-4094-b990-b4d8de7e1d61.png)

**Comment by bacherfl** [comment]
@ElliotDavis Thank you for the additional information. Is the upstream repository used for creating the project empty, or does this already contain a git history?

**Comment by rjrosa** [comment]
Hi Elliot.

It is a brand-new repo.

Thanks.




Robinson.

From: Florian Bacher ***@***.***>
Date: Monday, August 22, 2022 at 2:18 AM
To: keptn/keptn ***@***.***>
Cc: Robinson Rosa ***@***.***>, Mention ***@***.***>
Subject: Re: [keptn/keptn] When creating a new project fails. Error – creating project <PROJECT-NAME> failed. Project already exists. (Issue #8481)
@ElliotDavis Thank you for the additional information. Is the upstream repository used for creating the project empty, or does this already contain a git history? — Reply to this email directly, view it on GitHub, or unsubscribe ‍ ‍ ‍ ‍ ‍


@ElliotDavis<https://urldefense.com/v3/__https:/github.com/ElliotDavis__;!!CsXUvQARd5I!cGcCdGQd2a32XoGw6pB5VnhODawEnGzZBHFtywPm524VqDPvJ0y2PUmtNV1E6a4mkPfbVO7KJgK-yGAFINeJVytRGeegJg$> Thank you for the additional information. Is the upstream repository used for creating the project empty, or does this already contain a git history?

**Comment by thisthat** [comment]
This issue could be similar to https://github.com/keptn/keptn/issues/8159
This has been fixed in Keptn 0.17.0 - I would recommend updating to a more recent version of Keptn

**Comment by bacherfl** [comment]
@rjosa did the problem still occur after upgrading to a more recent version of Keptn?

**Comment by thisthat** [comment]
I am closing the issue since Keptn 0.17 should fix this problem, @rjrosa feel free to re-open it if the problem still occurs in your env w/ Keptn >= 0.17

**Comment by ElliotDavis** [comment]
I have deleted the repo and recreated it multiple times because I found
that little piece of information on one of the forums.  the APP token has
read/write as per the documents.  So each time it is a "fresh" repo with no
history.
Cheers,
Elliot Davis
***@***.***
626.502.7761
